# Generated by Django 5.1.5 on 2025-03-27 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(choices=[('ORIGIN', 'Povos dos campos, das águas, das florestas: agricultores(as), produtores(as), pescadores(as), indígenas, quilombolas'), ('ESTUDENT', 'Estudantes de nível médio e técnico'), ('DEGREE', 'Estudantes de curso superior'), ('POS', 'Estudantes de pós graduação'), ('TEACHER', 'Professores'), ('OTHERS', 'Outros profissionais')], default='ORIGIN', help_text='Escolha uma das opções dispóniveis', max_length=250, verbose_name='Atividade')),
                ('full_name', models.CharField(help_text='Maria José de Jesus', max_length=250, verbose_name='Nome')),
                ('entity', models.CharField(blank=True, help_text='IFPI', max_length=250, verbose_name='Entidade')),
                ('telephone', models.CharField(blank=True, help_text='(89) 98123-4567', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='mariajose@email.com', max_length=254, unique=True, verbose_name='E-mail')),
                ('workshop', models.CharField(choices=[('0', 'Não participarei de Oficina'), ('1', '1. Oficina Sementes da Fartura: Pureza, germinação, manejo e armazenagem'), ('2', '2. Introdução aos Sistemas Agroflorestais'), ('3', '3. Redesenho dos agroecossistemas familiares para a transição agroecológica e o fortalecimento dos sistemas agroalimentares'), ('4', '4. Introdução à meliponicultura'), ('5', '5. O uso do sistema agroflorestal na mitigação das mudanças climáticas'), ('6', '6. Bases gerais da pecuária orgânica e alimentação de aves, bovinos, suínos, caprinos e ovinos no sistema orgânico'), ('7', '7. Fontes alternativas para alimentação de aves caipiras'), ('8', '8. Preparações sustentáveis'), ('9', '9. A organização do campo para a produção agroecológica e as relações de gênero'), ('10', '10. Acesso dos jovens rurais aos espaços decisórios e de diálogo agroecologia'), ('11', '11. Manipulação de plantas medicinais'), ('12', '12. Formação de preços de venda de produtos da agricultura familiar')], help_text='Escolha uma das oficinas disponíveis', max_length=150, verbose_name='Oficina')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
