# Generated by Django 5.1.5 on 2025-03-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AddField(
            model_name='registration',
            name='confirmated',
            field=models.BooleanField(default=False, verbose_name='Inscrição Confirmada?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='activity',
            field=models.CharField(choices=[('ORIGIN', 'Povos dos campos, das águas, das florestas: agricultores(as), produtores(as), pescadores(as), indígenas, quilombolas'), ('ESTUDENT', 'Estudantes de nível médio e técnico'), ('DEGREE', 'Estudantes de curso superior'), ('POS', 'Estudantes de pós graduação'), ('TEACHER', 'Professores'), ('OTHERS', 'Outros profissionais')], default='ORIGIN', help_text='Escolha uma das opções disponíveis', max_length=250, verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(help_text='Exemplo: mariajose@email.com', max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='entity',
            field=models.CharField(blank=True, help_text='Exemplo: IFPI', max_length=250, verbose_name='Entidade'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.CharField(help_text='Exemplo: Maria José de Jesus', max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='telephone',
            field=models.CharField(blank=True, help_text='Exemplo: (89) 98123-4567', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='workshop',
            field=models.CharField(choices=[('0', 'Não participarei de Oficina'), ('1', '1. Oficina Sementes da Fartura: Pureza, germinação, manejo e armazenagem'), ('2', '2. Introdução aos Sistemas Agroflorestais'), ('3', '3. Redesenho dos agroecossistemas familiares para a transição agroecológica e o fortalecimento dos sistemas agroalimentares'), ('4', '4. Introdução à meliponicultura'), ('5', '5. O uso do sistema agroflorestal na mitigação das mudanças climáticas'), ('6', '6. Bases gerais da pecuária orgânica e alimentação de aves, bovinos, suínos, caprinos e ovinos no sistema orgânico'), ('7', '7. Fontes alternativas para alimentação de aves caipiras'), ('8', '8. Preparações sustentáveis'), ('9', '9. A organização do campo para a produção agroecológica e as relações de gênero'), ('10', '10. Acesso dos jovens rurais aos espaços decisórios e de diálogo agroecologia'), ('11', '11. Manipulação de plantas medicinais'), ('12', '12. Formação de preços de venda de produtos da agricultura familiar')], default='0', help_text='Escolha uma das oficinas disponíveis', max_length=150, verbose_name='Oficina'),
        ),
    ]
