# Generated by Django 5.1.7 on 2025-07-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registration_options_registration_confirmated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='organization',
            field=models.CharField(choices=[('NONE', 'Não faz parte da Organização'), ('PRESENTATION', 'Apresentação de Trabalhos'), ('MONITOR', 'Monitores'), ('COMMITTEE', 'Membro de Comissões')], default='NONE', help_text='Escolha uma das categorias de organização disponíveis', max_length=150, verbose_name='Organização'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(help_text='Exemplo: mariajose@email.com', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='workshop',
            field=models.CharField(choices=[('0', 'Não participarei de Oficina'), ('1', '1. Oficina Sementes da Fartura: Pureza, germinação, manejo, armazenagem e implantação de casas/bancos comunitários de sementes'), ('2', '2. Práticas Agroecológicas (água de vidro, biofertilizantes)'), ('3', '3. Redesenho dos agroecossistemas familiares para a transição agroecológica e o fortalecimento dos sistemas agroalimentares'), ('4', '4. Introdução à meliponicultura'), ('5', '5. Introdução aos Sistemas Agroflorestais (SAF) e o uso do SAF na mitigação das mudanças climáticas'), ('6', '6. Bases gerais da pecuária orgânica e alimentação de aves, bovinos, suínos, caprinos e ovinos no sistema orgânico'), ('7', '7. Fontes alternativas para alimentação de aves caipiras'), ('8', '8. Preparações sustentáveis'), ('9', '9. Agroecologica, cuidado e feminismo'), ('10', '10. Acesso dos jovens rurais aos espaços decisórios e de diálogo agroecologia'), ('11', '11. Manipulação de plantas bioativas'), ('12', '12. Formação de preços de venda de produtos da agricultura familiar')], default='0', help_text='Escolha uma das oficinas disponíveis', max_length=150, verbose_name='Oficina'),
        ),
    ]
