# Generated by Django 6.0 on 2026-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='activity',
            field=models.CharField(choices=[('ORIGIN', 'Comunidade / entusiasta de tecnologia'), ('ESTUDENT', 'Estudantes de nível médio e técnico'), ('DEGREE', 'Estudantes de curso superior'), ('POS', 'Estudantes de pós graduação'), ('TEACHER', 'Professores'), ('OTHERS', 'Outros profissionais')], default='ORIGIN', help_text='Escolha uma das opções disponíveis', max_length=250, verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='workshop',
            field=models.CharField(choices=[('0', 'Não participarei de minicurso'), ('1', '1. Introdução ao Desenvolvimento Web'), ('2', '2. Dados e Python na Prática'), ('3', '3. Nuvem e DevOps para Iniciantes'), ('4', '4. Design de Interfaces & Figma'), ('5', '5. Segurança da Informação na Prática'), ('6', '6. Construindo APIs com Node.js')], default='0', help_text='Escolha um dos minicursos disponíveis', max_length=150, verbose_name='Minicurso'),
        ),
    ]
