# Generated by Django 6.0 on 2026-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_registration_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='workshop',
            field=models.CharField(choices=[('0', 'Não participarei de minicurso'), ('1', '1. Django Girls'), ('2', '2. Teste de Software'), ('3', '3. Desenvolvimento de Games')], default='0', help_text='Escolha um dos minicursos disponíveis', max_length=150, verbose_name='Minicurso'),
        ),
    ]
