# Generated by Django 6.0 on 2026-09-26 19:04

import core.email_templates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_registration_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_recipient', models.EmailField(blank=True, help_text='Se vazio, usa o DEFAULT_FROM_EMAIL configurado no servidor.', max_length=254, verbose_name='Receber mensagens de contato em')),
                ('received_subject', models.CharField(default='Capivara Tech — inscrição recebida', max_length=255, validators=[core.email_templates.validate_email_subject], verbose_name='Assunto: inscrição recebida')),
                ('received_body', models.TextField(default='Olá, ${nome}!\n\nRecebemos sua inscrição no Capivara Tech.\nMinicurso: ${minicurso}\n\nAguarde a confirmação da organização.\n\nEquipe Capivara Tech', help_text='Texto simples. Variáveis: ${nome}, ${email}, ${minicurso}, ${protocolo}. Use $$ para escrever um cifrão.', validators=[core.email_templates.validate_email_template], verbose_name='Mensagem: inscrição recebida')),
                ('confirmed_subject', models.CharField(default='Capivara Tech — inscrição confirmada', max_length=255, validators=[core.email_templates.validate_email_subject], verbose_name='Assunto: inscrição confirmada')),
                ('confirmed_body', models.TextField(default='Olá, ${nome}!\n\nSua inscrição no Capivara Tech foi confirmada!\nMinicurso: ${minicurso}\nProtocolo: ${protocolo}\n\nEsperamos você!\nEquipe Capivara Tech', help_text='Texto simples. Variáveis: ${nome}, ${email}, ${minicurso}, ${protocolo}. Use $$ para escrever um cifrão.', validators=[core.email_templates.validate_email_template], verbose_name='Mensagem: inscrição confirmada')),
            ],
            options={
                'verbose_name': 'Configurações de email',
                'verbose_name_plural': 'Configurações de email',
            },
        ),
    ]
