# Generated by Django 6.0 on 2026-09-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='contact_recipient',
            field=models.EmailField(blank=True, default='contato@sistemasparainternet.com', help_text='Se vazio, envia para contato@sistemasparainternet.com.', max_length=254, verbose_name='Receber mensagens de contato em'),
        ),
    ]
