# Generated by Django 6.0 on 2026-09-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_emailsettings_contact_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('session', models.CharField(blank=True, help_text='Ex.: "Palestra 3" ou "Minicurso 2".', max_length=150, verbose_name='Sessão')),
                ('role', models.CharField(blank=True, help_text='Aparece ao lado da sessão. Ex.: "Analista de Redes" ou "Django Girls".', max_length=250, verbose_name='Cargo ou minicurso')),
                ('talk', models.CharField(blank=True, help_text='Aparece entre aspas no início da descrição.', max_length=250, verbose_name='Tema da palestra')),
                ('bio', models.TextField(blank=True, help_text='Deixe uma linha em branco para separar parágrafos.', verbose_name='Descrição')),
                ('photo', models.ImageField(blank=True, help_text='JPG ou PNG, de preferência quadrada e com o rosto no centro. Sem foto, o site mostra uma imagem padrão.', upload_to='speakers', verbose_name='Foto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Números menores aparecem primeiro.', verbose_name='Ordem')),
                ('published', models.BooleanField(default=True, verbose_name='Exibir no site')),
            ],
            options={
                'verbose_name': 'Palestrante ou instrutor',
                'verbose_name_plural': 'Palestrantes e instrutores',
                'ordering': ('order', 'id'),
            },
        ),
    ]
