# Generated by Django 6.0 on 2026-09-26 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_import_existing_speakers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('subtitle', models.CharField(blank=True, help_text='Ex.: "Minicursos" ou "Palestras".', max_length=100, verbose_name='Subtítulo da aba')),
                ('published', models.BooleanField(default=True, verbose_name='Exibir no site')),
            ],
            options={
                'verbose_name': 'Dia da programação',
                'verbose_name_plural': 'Programação',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identifica o minicurso em cada inscrição. Não pode ser alterado depois de criado.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$', 'Use só números, sem zero à esquerda (o 0 é reservado para "não participarei de minicurso").')], verbose_name='Código')),
                ('name', models.CharField(max_length=250, verbose_name='Nome do minicurso')),
                ('instructors', models.CharField(blank=True, help_text='Aparece no card do site. Ex.: "João Dias" ou "Django Girls".', max_length=250, verbose_name='Ministrante(s)')),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Ao atingir esse número de inscritos, o minicurso deixa de aparecer no formulário de inscrição.', verbose_name='Vagas')),
                ('order', models.PositiveIntegerField(default=0, help_text='Números menores aparecem primeiro.', verbose_name='Ordem')),
                ('published', models.BooleanField(default=True, help_text='Desmarque para esconder. As inscrições já feitas continuam ligadas a este minicurso.', verbose_name='Exibir no site e na inscrição')),
            ],
            options={
                'verbose_name': 'Minicurso',
                'verbose_name_plural': 'Minicursos',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='registration',
            name='workshop',
            field=models.CharField(default='0', help_text='Escolha um dos minicursos disponíveis', max_length=150, verbose_name='Minicurso'),
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Término')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Ex.: "Auditório · Nome do palestrante" ou "Lab 1".', max_length=250, verbose_name='Local e responsável')),
                ('tag', models.CharField(choices=[('minicurso', 'Minicurso'), ('palestra', 'Palestra'), ('keynote', 'Keynote'), ('painel', 'Painel'), ('pausa', 'Pausa'), ('abertura', 'Abertura'), ('social', 'Social'), ('parceiro', 'Parceiro'), ('cultura', 'Cultura')], default='palestra', max_length=20, verbose_name='Etiqueta')),
                ('order', models.PositiveIntegerField(default=0, help_text='Só serve para desempatar itens que começam na mesma hora.', verbose_name='Ordem no mesmo horário')),
                ('published', models.BooleanField(default=True, verbose_name='Exibir no site')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.eventday', verbose_name='Dia')),
            ],
            options={
                'verbose_name': 'Item da programação',
                'verbose_name_plural': 'Itens da programação',
                'ordering': ('start_time', 'order', 'id'),
            },
        ),
    ]
