import datetime

from django.db import migrations

WORKSHOPS = [{'code': '1',
  'name': 'Django Girls',
  'instructors': 'Django Girls',
  'capacity': 30,
  'order': 10,
  'published': True},
 {'code': '2',
  'name': 'Teste de Software',
  'instructors': 'João Dias',
  'capacity': 30,
  'order': 20,
  'published': True},
 {'code': '3',
  'name': 'Desenvolvimento de Games',
  'instructors': 'Wanderson Paes',
  'capacity': 30,
  'order': 30,
  'published': True}]

DAYS = [{'date': '2026-10-21',
  'subtitle': 'Minicursos',
  'items': [{'start': '12:00',
             'end': '14:00',
             'title': 'Credenciamento',
             'subtitle': 'Lab 1 / Lab 2',
             'tag': 'abertura',
             'order': 0},
            {'start': '14:00',
             'end': '17:30',
             'title': 'Minicurso 1 — Django Girls',
             'subtitle': 'Lab 1',
             'tag': 'minicurso',
             'order': 1},
            {'start': '14:00',
             'end': '17:30',
             'title': 'Minicurso 2 — Teste de Software',
             'subtitle': 'Lab 2 · João Dias',
             'tag': 'minicurso',
             'order': 2},
            {'start': '17:30',
             'end': '18:00',
             'title': 'Coffee-break',
             'subtitle': 'Intervalo',
             'tag': 'pausa',
             'order': 3},
            {'start': '18:00',
             'end': '22:00',
             'title': 'Minicurso 1 (continuação) — Django Girls',
             'subtitle': 'Lab 1',
             'tag': 'minicurso',
             'order': 4},
            {'start': '18:00',
             'end': '22:00',
             'title': 'Minicurso 3 — Desenvolvimento de Games',
             'subtitle': 'Lab 2 · Wanderson Paes',
             'tag': 'minicurso',
             'order': 5}]},
 {'date': '2026-10-22',
  'subtitle': 'Palestras',
  'items': [{'start': '12:00',
             'end': '14:00',
             'title': 'Credenciamento',
             'subtitle': 'Hall de entrada',
             'tag': 'abertura',
             'order': 0},
            {'start': '14:00',
             'end': '16:00',
             'title': 'Abertura + Palestra 1 — Introdução a AWS',
             'subtitle': 'Auditório · Eduardo Neri Martins',
             'tag': 'keynote',
             'order': 1},
            {'start': '16:00',
             'end': '17:30',
             'title': 'Palestra 2 — Propriedade Intelectual',
             'subtitle': 'Auditório · Aldo Victor D. Oliveira',
             'tag': 'palestra',
             'order': 2},
            {'start': '17:30',
             'end': '18:00',
             'title': 'Coffee-break',
             'subtitle': 'Intervalo',
             'tag': 'pausa',
             'order': 3},
            {'start': '18:00',
             'end': '20:00',
             'title': 'Momento OxenteNet',
             'subtitle': 'Patrocinador master',
             'tag': 'parceiro',
             'order': 4},
            {'start': '20:00',
             'end': '22:00',
             'title': 'Mesa-redonda — Problemas Locais',
             'subtitle': 'Auditório · Janio',
             'tag': 'painel',
             'order': 5}]},
 {'date': '2026-10-23',
  'subtitle': 'Palestras & Encerramento',
  'items': [{'start': '12:00',
             'end': '14:00',
             'title': 'Credenciamento',
             'subtitle': 'Hall de entrada',
             'tag': 'abertura',
             'order': 0},
            {'start': '14:00',
             'end': '16:00',
             'title': 'Sebrae',
             'subtitle': 'A confirmar',
             'tag': 'parceiro',
             'order': 1},
            {'start': '16:00',
             'end': '17:30',
             'title': 'Palestra 3',
             'subtitle': 'Auditório · Bianca Freire Marques',
             'tag': 'palestra',
             'order': 2},
            {'start': '17:30',
             'end': '18:00',
             'title': 'Coffee-break',
             'subtitle': 'Intervalo',
             'tag': 'pausa',
             'order': 3},
            {'start': '18:00',
             'end': '19:00',
             'title': 'Palestra 4 — Introdução a Visão Computacional',
             'subtitle': 'Auditório · Justino Duarte',
             'tag': 'palestra',
             'order': 4},
            {'start': '20:00',
             'end': '22:00',
             'title': 'Palestra 5 & Encerramento',
             'subtitle': 'Auditório · Rangel',
             'tag': 'keynote',
             'order': 5}]}]


def import_existing_content(apps, schema_editor):
    Workshop = apps.get_model("core", "Workshop")
    EventDay = apps.get_model("core", "EventDay")
    ScheduleItem = apps.get_model("core", "ScheduleItem")

    if not Workshop.objects.exists():
        for data in WORKSHOPS:
            Workshop.objects.create(**data)

    if not EventDay.objects.exists():
        for data in DAYS:
            day = EventDay.objects.create(
                date=datetime.date.fromisoformat(data["date"]),
                subtitle=data["subtitle"],
            )
            for item in data["items"]:
                ScheduleItem.objects.create(
                    day=day,
                    start_time=datetime.time.fromisoformat(item["start"]),
                    end_time=datetime.time.fromisoformat(item["end"]) if item["end"] else None,
                    title=item["title"],
                    subtitle=item["subtitle"],
                    tag=item["tag"],
                    order=item["order"],
                )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_workshops_and_schedule"),
    ]

    operations = [
        migrations.RunPython(import_existing_content, migrations.RunPython.noop),
    ]
