# Generated by Django 6.0 on 2026-09-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_link_existing_workshop_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workload',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Carga horária do certificado (horas)'),
        ),
    ]
