# Generated by Django 6.0 on 2026-10-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_workshop_workload'),
        ('django_tasks_database', '0016_remove_dbtaskresult_django_task_new_ordering_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100, verbose_name='Tipo de email')),
                ('subject', models.TextField(verbose_name='Assunto')),
                ('recipients', models.JSONField(default=list, verbose_name='Destinatários')),
                ('from_email', models.TextField(verbose_name='Remetente')),
                ('reply_to', models.JSONField(default=list, verbose_name='Responder para')),
                ('body', models.TextField(verbose_name='Conteúdo enviado (texto)')),
                ('status', models.CharField(choices=[('sending', 'Enviando'), ('sent', 'Aceito pelo servidor de email'), ('failed', 'Falhou')], default='sending', max_length=20, verbose_name='Estado')),
                ('error', models.TextField(blank=True, verbose_name='Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tentativa em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='django_tasks_database.dbtaskresult')),
            ],
            options={
                'verbose_name': 'Histórico de email',
                'verbose_name_plural': 'Histórico de emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
