# Generated by Django 6.0 on 2026-10-04 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_emaildelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('subtitle', models.CharField(blank=True, help_text='Aparece embaixo do nome quando não há logo. Ex.: "Coronel José Dias".', max_length=250, verbose_name='Complemento')),
                ('logo', models.ImageField(blank=True, help_text='PNG ou JPG, de preferência com pouca margem em volta. Sem logo, o site mostra o nome em um cartão de texto.', upload_to='sponsors', verbose_name='Logo')),
                ('website', models.URLField(blank=True, help_text='Opcional. Se preenchido, o cartão vira um link.', verbose_name='Site ou rede social')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Uso interno: o valor NÃO aparece no site. Define o destaque: a partir de R$ 500 é Ouro, a partir de R$ 300 é Prata e abaixo disso é Bronze.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do patrocínio (R$)')),
                ('is_master', models.BooleanField(default=False, help_text='Fica no topo, no maior destaque, independente do valor.', verbose_name='Patrocinador master')),
                ('published', models.BooleanField(default=True, verbose_name='Exibir no site')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'ordering': ('-is_master', '-amount', 'name'),
            },
        ),
    ]
