# Generated by Django 5.1.7 on 2025-12-08 18:47

import django.utils.timezone
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_name', models.CharField(help_text='Exemplo: Maria José de Jesus', max_length=250, verbose_name='Nome do Participante')),
                ('participant_email', models.EmailField(help_text='Exemplo: mariajosedejesus@mail.com', max_length=254, verbose_name='E-mail do Participante')),
                ('activity', models.CharField(help_text='Exemplo: Organização Geral', max_length=250, verbose_name='Atividade')),
                ('workload', models.PositiveIntegerField(help_text='Exemplo: 4 (horas)', verbose_name='Carga Horaria')),
                ('location', models.CharField(help_text='Exemplo: São Raimundo Nonato', max_length=250, verbose_name='Local')),
                ('date', models.DateField(verbose_name='Data de Emissão')),
                ('certifier_name', models.CharField(help_text='Exemplo: Deus Todo Poderoso', max_length=250, verbose_name='Nome do Certificador')),
                ('certifier_position', models.CharField(help_text='Exemplo: Criador de Tudo e de Todos', max_length=250, verbose_name='Cargo do Certificador')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(help_text='<h3>Variáveis Disponíveis:</h3><br />\n<b>{Nome_Participante}</b> Nome Completo do Participante.<br />\n<b>{Atividade}</b> Nome da Atividade.<br />\n<b>{Carga_Horaria}</b> Carga Horária da Atividade.<br />\n<b>{Local_de_Emissão}</b> Localização do Evento.<br />\n<b>{Data_de_Emissão}</b> Data de Emissão do Certificado.<br />\n<b>{Nome_Certificador}</b> Nome Completo do Certificador.<br />\n<b>{Cargo_Certificador}</b> Cargo/Função do Certificador.<br />\n<hr />\n<b>Exemplo:</b><br />\n\n<p style="text-align:justify;">\n    Declaro que <strong>{{Nome_Participante}}</strong> participou do <strong>{{Atividade}}</strong> com carga horaria de <strong>{{Carga_Horaria}}</strong> horas.\n</p>\n<p style="text-align:right;">\n    <br>\n    <strong>{{Local_de_Emissão}}, {{Data_de_Emissão}}</strong>\n</p>\n<p style="text-align:center;">\n    <br>\n    <strong>{{Nome_Certificador}}</strong><br>\n    <strong>{{Cargo_Certificador}}</strong><br>\n    &nbsp;\n</p>\n\n', verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.CreateModel(
            name='CertificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_location', models.CharField(default='São Raimundo Nonato', max_length=255, verbose_name='Local de Emissão')),
                ('default_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('default_certifier_name', models.CharField(default='Nome do Certificador', max_length=255, verbose_name='Nome do Certificador')),
                ('default_certifier_position', models.CharField(default='Cargo do Certificador', max_length=255, verbose_name='Cargo do Certificador')),
                ('default_background_image', models.ImageField(default='', upload_to='settings', verbose_name='Imagem de Fundo')),
                ('default_text', django_ckeditor_5.fields.CKEditor5Field(default='\n<p style="text-align:justify;">\n    Declaro que <strong>{{Nome_Participante}}</strong> participou do <strong>{{Atividade}}</strong> com carga horaria de <strong>{{Carga_Horaria}}</strong> horas.\n</p>\n<p style="text-align:right;">\n    <br>\n    <strong>{{Local_de_Emissão}}, {{Data_de_Emissão}}</strong>\n</p>\n<p style="text-align:center;">\n    <br>\n    <strong>{{Nome_Certificador}}</strong><br>\n    <strong>{{Cargo_Certificador}}</strong><br>\n    &nbsp;\n</p>\n', help_text='<h3>Variáveis Disponíveis:</h3><br />\n<b>{Nome_Participante}</b> Nome Completo do Participante.<br />\n<b>{Atividade}</b> Nome da Atividade.<br />\n<b>{Carga_Horaria}</b> Carga Horária da Atividade.<br />\n<b>{Local_de_Emissão}</b> Localização do Evento.<br />\n<b>{Data_de_Emissão}</b> Data de Emissão do Certificado.<br />\n<b>{Nome_Certificador}</b> Nome Completo do Certificador.<br />\n<b>{Cargo_Certificador}</b> Cargo/Função do Certificador.<br />\n<hr />\n<b>Exemplo:</b><br />\n\n<p style="text-align:justify;">\n    Declaro que <strong>{{Nome_Participante}}</strong> participou do <strong>{{Atividade}}</strong> com carga horaria de <strong>{{Carga_Horaria}}</strong> horas.\n</p>\n<p style="text-align:right;">\n    <br>\n    <strong>{{Local_de_Emissão}}, {{Data_de_Emissão}}</strong>\n</p>\n<p style="text-align:center;">\n    <br>\n    <strong>{{Nome_Certificador}}</strong><br>\n    <strong>{{Cargo_Certificador}}</strong><br>\n    &nbsp;\n</p>\n\n', verbose_name='Texto do Certificado')),
            ],
            options={
                'verbose_name': ' Configurações de Certificados',
            },
        ),
    ]
