# Generated by Django 6.0 on 2026-09-26 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Copiada das configurações ao gerar. Se vazia, usa o fundo atual das configurações.', upload_to='certificates', verbose_name='Imagem de fundo'),
        ),
        migrations.AddField(
            model_name='certificationsettings',
            name='margin_bottom',
            field=models.PositiveSmallIntegerField(default=45, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Margem inferior do texto (mm)'),
        ),
        migrations.AddField(
            model_name='certificationsettings',
            name='margin_left',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Margem esquerda do texto (mm)'),
        ),
        migrations.AddField(
            model_name='certificationsettings',
            name='margin_right',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Margem direita do texto (mm)'),
        ),
        migrations.AddField(
            model_name='certificationsettings',
            name='margin_top',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Margem superior do texto (mm)'),
        ),
        migrations.AlterField(
            model_name='certificationsettings',
            name='default_background_image',
            field=models.ImageField(blank=True, default='', help_text='Fundo A4 horizontal (proporção 297 × 210). Opcional.', upload_to='settings', verbose_name='Imagem de Fundo'),
        ),
    ]
