# Generated by Django 6.0 on 2026-09-26 20:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_certificate_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='<h3>Variáveis Disponíveis:</h3><br />\n<b>{{Nome_Participante}}</b> Nome Completo do Participante.<br />\n<b>{{Atividade}}</b> Nome da Atividade.<br />\n<b>{{Carga_Horaria}}</b> Carga Horária da Atividade.<br />\n<b>{{Local_de_Emissão}}</b> Localização do Evento.<br />\n<b>{{Data_de_Emissão}}</b> Data de Emissão do Certificado.<br />\n<b>{{Nome_Certificador}}</b> Nome Completo do Certificador.<br />\n<b>{{Cargo_Certificador}}</b> Cargo/Função do Certificador.<br />\n<hr />\n<b>Exemplo:</b><br />\n\n<p style="text-align:justify;">\n    Declaro que <strong>{{Nome_Participante}}</strong> participou do <strong>{{Atividade}}</strong> com carga horaria de <strong>{{Carga_Horaria}}</strong> horas.\n</p>\n<p style="text-align:right;">\n    <br>\n    <strong>{{Local_de_Emissão}}, {{Data_de_Emissão}}</strong>\n</p>\n<p style="text-align:center;">\n    <br>\n    <strong>{{Nome_Certificador}}</strong><br>\n    <strong>{{Cargo_Certificador}}</strong><br>\n    &nbsp;\n</p>\n\n', verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='certificationsettings',
            name='default_text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='\n<p style="text-align:justify;">\n    Declaro que <strong>{{Nome_Participante}}</strong> participou do <strong>{{Atividade}}</strong> com carga horaria de <strong>{{Carga_Horaria}}</strong> horas.\n</p>\n<p style="text-align:right;">\n    <br>\n    <strong>{{Local_de_Emissão}}, {{Data_de_Emissão}}</strong>\n</p>\n<p style="text-align:center;">\n    <br>\n    <strong>{{Nome_Certificador}}</strong><br>\n    <strong>{{Cargo_Certificador}}</strong><br>\n    &nbsp;\n</p>\n', help_text='<h3>Variáveis Disponíveis:</h3><br />\n<b>{{Nome_Participante}}</b> Nome Completo do Participante.<br />\n<b>{{Atividade}}</b> Nome da Atividade.<br />\n<b>{{Carga_Horaria}}</b> Carga Horária da Atividade.<br />\n<b>{{Local_de_Emissão}}</b> Localização do Evento.<br />\n<b>{{Data_de_Emissão}}</b> Data de Emissão do Certificado.<br />\n<b>{{Nome_Certificador}}</b> Nome Completo do Certificador.<br />\n<b>{{Cargo_Certificador}}</b> Cargo/Função do Certificador.<br />\n<hr />\n<b>Exemplo:</b><br />\n\n<p style="text-align:justify;">\n    Declaro que <strong>{{Nome_Participante}}</strong> participou do <strong>{{Atividade}}</strong> com carga horaria de <strong>{{Carga_Horaria}}</strong> horas.\n</p>\n<p style="text-align:right;">\n    <br>\n    <strong>{{Local_de_Emissão}}, {{Data_de_Emissão}}</strong>\n</p>\n<p style="text-align:center;">\n    <br>\n    <strong>{{Nome_Certificador}}</strong><br>\n    <strong>{{Cargo_Certificador}}</strong><br>\n    &nbsp;\n</p>\n\n', verbose_name='Texto do Certificado'),
        ),
    ]
